apiVersion: v2
name: configmap-operator
description: Helm chart for configmap-operator based on helm-apps library
type: application
version: 0.3.1
appVersion: "0.3.1"
dependencies:
  - name: helm-apps
    version: ~1
    repository: "https://alvnukov.github.io/helm-apps"
